<?php
$files = [
    'user_creation.php', 'task_tracking.php', 'settings.php', 'reports.php',
    'profile_update.php', 'overdue_report.php', 'notifications.php',
    'graph.php', 'dashboard.php', 'create_task.php', 'blank_wrushabh.php',
    'announcements.php'
];

foreach ($files as $file) {
    if (!file_exists($file)) continue;
    
    $content = file_get_contents($file);
    $original = $content;

    // 1. Replace the a href generated by lang_switch_url
    $content = preg_replace(
        '/<a\s+href="<\?php\s+echo\s+htmlspecialchars\(\$lang_switch_url\);\s*\?>"\s*class="/s',
        '<a href="#" class="lang-switch-btn ',
        $content
    );

    // 2. Replace hardcoded links with lang toggle
    $content = preg_replace(
        '/<a\s+href="[^"]*\?lang=[^"]*"\s*class="([^"]*)">\s*(<i\s+data-lucide="languages")/si',
        '<a href="#" class="lang-switch-btn $1"> $2',
        $content
    );

    // 3. Replace <button> language toggles
    $content = preg_replace(
        '/<button\s+class="([^"]*)">\s*<i\s+data-lucide="languages"/si',
        '<button class="lang-switch-btn $1"> <i data-lucide="languages"',
        $content
    );

    if ($content !== $original) {
        file_put_contents($file, $content);
        echo "Fixed $file\n";
    }
}
?>
